name = "GeoCotrans"
uuid = "4624b3bc-fe35-44f8-bfa8-722ff9c0e307"
version = "0.2.1"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SatelliteToolboxLegendre = "7fa26607-a272-47b2-9aa2-a6c1d419d9d2"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[extensions]
GeoCotransDimensionalDataExt = "DimensionalData"

[compat]
Bumper = "0.7"
Dates = "1"
DimensionalData = "0.29"
LazyArrays = "2"
LinearAlgebra = "1"
PrecompileTools = "1"
SatelliteToolboxLegendre = "1.1"
SpaceDataModel = "0.2.4"
StaticArrays = "1"
julia = "1.10"
